### ISSUE TITLE
PHP V7.3.0 LDAP_OPT_PROTOCOL_VERSION

### ISSUE THREAD

**Issue by cyjobes** [DirectoryTree/LdapRecord-Discussions#13]
I'm getting an error mentioning LDAP_OPT_PROTOCOL_VERSION

```
ErrorException
Use of undefined constant LDAP_OPT_PROTOCOL_VERSION - assumed 'LDAP_OPT_PROTOCOL_VERSION' (this will throw an Error in a future version of PHP)
```

Knowing this might throw an error, has there been a fix?

I know that LDAP is installed with my version of php, which is 7.3.0

Please help.

**Comment by stevebauman** [comment]
Hi @cyjobes,

This error is in-fact because your PHP installation **does not** have the LDAP extension enabled.

I am 100% percent certain — as this exception is only thrown in this case.

The installation of PHP that your `composer` is using is likely a different installation that what your web server is using.

Hope this helps!

**Comment by cyjobes** [comment]
Would you know how I can get the extension and install it for MAMP?

**Comment by stevebauman** [comment]
LDAP comes bundled with most PHP installations by default. You simply need to enable it in MAMP.

Here's a guide showing you how to enable extensions on MAMP: https://jellystyle.com/2012/12/installing-php-extensions-with-mamp

Hope this helps!
